[versions]
kotlin = "2.1.20"

[plugins]
android-application = { id = "com.android.application" }
android-library = { id = "com.android.library" }
jvm = { id = "org.jetbrains.kotlin.jvm" }
kotlin = { id = "org.jetbrains.kotlin.android" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }